theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
continue-comments = false
line-number = "relative"
popup-border = "menu"
rainbow-brackets = true
trim-final-newlines = true
trim-trailing-whitespace = true
true-color = true
undercurl = true

[editor.auto-save.after-delay]
enable = true
timeout = 1000

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["line-numbers", "spacer", "diagnostics"]

[editor.indent-guides]
character = "·"
render = true
skip-levels = 2

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true
display-progress-messages = true
display-signature-help-docs = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = false
wrap-indicator = ""

[editor.statusline]
left = ["mode", "file-base-name", "read-only-indicator", "file-modification-indicator"]
right = [
    "diagnostics",
    "current-working-directory",
    "register",
    "position",
    "total-line-numbers",
    "file-encoding",
    "spinner",
]

[editor.word-completion]
trigger-length = 4

[keys.insert]
C-backspace = "delete_word_backward"
C-w = "delete_word_backward"

[keys.normal]
"$" = "goto_line_end"
"=" = ":format"
A-c = "toggle_block_comments"
G = "goto_last_line"
K = "signature_help"
a = ["append_mode", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
i = ["insert_mode", "collapse_selection"]

[keys.normal.m]
a = "surround_add"
s = "select_textobject_around"

[keys.normal.space]
"," = ":buffer-previous"
"." = ":buffer-next"
E = "file_explorer"
F = "file_picker"
e = "file_explorer_in_current_buffer_directory"
f = "file_picker_in_current_directory"
x = ":buffer-close"

[keys.select]
"$" = "goto_line_end"
C-c = "toggle_block_comments"
G = "goto_last_line"

[keys.select.m]
a = "surround_add"
s = "select_textobject_around"
