local data = {}

data.mode_icons = {
    ["n"] = "  ",
    ["i"] = "  ",
    ["s"] = "  ",
    ["S"] = "  ",
    [""] = "  ",

    ["v"] = "  ",
    ["V"] = "  ",
    [""] = "  ",
    ["r"] = " ﯒ ",
    ["r?"] = "  ",
    ["c"] = "  ",
    ["t"] = "  ",
    ["!"] = "  ",
    ["R"] = "  ",
}

data.file_icons = {
    typescript = " ",
    json = " ",
    jsonc = " ",
    tex = "ﭨ ",
    ts = " ",
    python = " ",
    py = " ",
    java = " ",
    html = " ",
    css = " ",
    scss = " ",
    javascript = " ",
    js = " ",
    javascriptreact = " ",
    markdown = " ",
    md = " ",
    sh = " ",
    zsh = " ",
    vim = " ",
    rust = " ",
    rs = " ",
    cpp = " ",
    c = " ",
    go = " ",
    lua = " ",
    conf = " ",
    haskel = " ",
    hs = " ",
    ruby = " ",
    norg = " ",
    txt = " ",
}

return data
